update: docker-compose
inqueryio/inquery pull request #25
Opened 2023-03-18 06:38 UTC by AkshayAwate

Added postgres docker container in docker-compose, which helps to setup inquery quickly and test it out.

2023-03-20 18:13 UTC, ciminelli requested changes
Looks good! Just one small comment to address. Thanks for jumping on this :)

2023-03-20 18:13 UTC, ciminelli commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=postgres
Can we leave this commented-out with a note that it can be enabled for testing purposes? Installs might already have a Postgres instance running so we don't want to have this in those cases.

2023-03-21 06:55 UTC, AkshayAwate commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=postgres
Made comments @ciminelli .

2023-03-21 16:28 UTC, ciminelli approved these changes
LGTM!

2023-03-21 16:32 UTC, merged