Display connection error if front end cannot connect to API server #11
inqueryio/inquery pull request #26
Opened 2023-04-08 12:36 UTC by D-Lite

https://user-images.githubusercontent.com/44473671/230721270-2b1eae44-d5ba-4d51-91f4-fa47ef75e8bf.mp4

Display connection error if front end cannot connect to API server:
 - Created a universal page guard that is used at the route level for each page highly dependent on the BE
 - Improvement on the loader ensuring health check is complete before any additional information.

2023-04-14 00:06 UTC, ciminelli commented on frontend/src/util/HealthCheck.js
> +        <LoadingOverlay active={loading} spinner={true} text="Loading..." />
Is this the same loading overlay that is in the test plan video or is this the loading overlay that was used before?

2023-04-14 00:07 UTC, ciminelli reviewed
Looking great! One small comment then I think we should be good to go :D

2023-04-14 01:33 UTC, D-Lite commented on frontend/src/util/HealthCheck.js
> +        <LoadingOverlay active={loading} spinner={true} text="Loading..." />
I made the wrong upload, thanks for pointing that out, I will replace it soon and we can proceed!

2023-04-14 02:00 UTC, D-Lite commented
https://user-images.githubusercontent.com/44473671/231922458-7d13e89d-942d-4e32-bc84-5565d3d6f3e4.mp4

Loading overlay video

2023-04-14 17:13 UTC, ciminelli commented
@D-Lite one thing I noticed is that the error page exists on http://localhost:3000/welcome

So after the connection issue is resolved the user is taken back there. Can you look into making it so the error is displayed on the same route the user is on?

2023-04-17 20:50 UTC, D-Lite commented
@ciminelli , thanks for that review, I was away from my PC during the weekend. Yes, the error page exists on every route aside main route  "/". So I just included it in our HealthCheck guided route and we should be able to see the error on the "/" route instead of navigating to the "/welcome" route.

2023-04-18 00:12 UTC, ciminelli requested changes
Looking good! Just one small fix and we can merge.

2023-04-18 00:12 UTC, ciminelli commented on frontend/src/App.js
> +          <Route exact path="/">
It looks like `/audit` was removed here if you can add it back!

2023-04-18 00:34 UTC, D-Lite commented
Thanks for that!
Fixed

2023-04-18 19:48 UTC, ciminelli approved these changes
![looksfine](https://user-images.githubusercontent.com/11033848/232889200-abdcaba5-8983-4258-9229-1f0d5aef5ded.gif)

2023-04-18 19:48 UTC, merged